version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./_log/nginx:/var/log/nginx
    ports:
      - 80:80
    links:
      - fluentd

  fluentd:
    build:
      context: .
      dockerfile: fluentd/Dockerfile
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./_log/nginx:/var/log/nginx
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:5.3.0-alpine
    ports:
      - 9200:9200

  kibana:
    image: kibana:5.3.0
    links:
      - "elasticsearch"
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
