version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./_log/nginx:/var/log/nginx
    ports:
      - 80:80
    links:
      - fluentd

  fluentd:
    build:
      context: .
      dockerfile: fluentd/Dockerfile
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./_log/nginx:/var/log/nginx
    ports:
      - "24224:24224"
      - "24224:24224/udp"
